// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import EditorController from "./editor_controller.js"
application.register("editor", EditorController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)
